/*
 This file is auto-generated by the statrep package.
 Do not edit this file or your changes will be lost.
 Edit the LaTeX file instead.
 
 See the statrep package documentation and the file
 statrep.cfg for information on these settings.
 */
 
 
%include "/folders/myshortcuts/report-example/code/analysis_SR_preamble.sas" /nosource;
/* Remove all output files. */
%cleandir(/folders/myshortcuts/report-example/code, tex, tex);
%cleandir(/folders/myshortcuts/report-example/code, png, png);
%cleandir(/folders/myshortcuts/report-example/code, lst, lst);


/* Start program with a null title. */
title;

libname data "/folders/myshortcuts/report-example/data";

filename reffile
  '/folders/myshortcuts/report-example/data/star-wars-survey-538.csv';

proc import datafile=reffile
dbms=csv
replace
out=data.starwars;
getnames=yes;
run;

data data;
 set data.starwars;
  if Jar_Jar_Binks in (" ", "Unfamiliar (N/A)")
    then wrong_jar_jar = " ";
  else if Jar_Jar_Binks in ("Very favorably","Somewhat favorably")
    then wrong_jar_jar = 1;
    else wrong_jar_jar = 0;
  if shot_first = "Han"
    then wrong_han = 0;
  if shot_first = "Greedo"
    then wrong_han = 1;
  if education in ("Bachelor degree", "Graduate degree")
    then college = "College degree";
  if education in ("Some college or Associate degree",
    "High school degree", "Less than high school degree")
    then college = "No college degree";
run;


%output(freq)
ods graphics on;

proc freq data = data;
table wrong_han wrong_jar_jar;
run;

ods graphics off;

%endoutput(freq)

%write(freqtabhan,store=freq,objects=Freq.Table1.OneWayFreqs,type=listing) 

%write(freqtabjar,store=freq,objects=Freq.Table2.OneWayFreqs,type=listing) 

%output(logistic)
ods graphics on;

proc logistic data = data plots = oddsratio;
 class age (ref = FIRST) gender college Star_Trek_fan;
 model wrong_han(event = "1") = age gender college Star_Trek_fan;
run;

ods graphics off;

%endoutput(logistic)

%output(logisticj)
ods graphics on;

proc logistic data = data plots = oddsratio;
 class age (ref = FIRST) gender college Star_Trek_fan;
 model wrong_jar_jar(event = "1") = age gender college Star_Trek_fan;
run;

ods graphics off;

%endoutput(logisticj)

%write(logisticOR,store=logistic,objects=OddsRatios,type=listing) 

%write(ORplot,store=logistic,objects=ORPlot,type=graphic) 

%write(logisticORj,store=logisticj,objects=OddsRatios,type=listing) 

%write(ORplotj,store=logisticj,objects=ORPlot,type=graphic) 

proc export data=data.starwars
   outfile =
     '/folders/myshortcuts/report-example/data/starwars_sasedit.csv'
   replace
   dbms = dlm;
   delimiter = ',';
run;

